### PR TITLE
[Refactor] Preventing Unnecessary Object Creation and Using Utility Methods

### PR DESCRIPTION
**Pull request by dukbong**
## What's changed?

- Improved readability by preventing unnecessary object creation and utilizing utility methods.
- Translated from Chinese to English.
    - The translation work is not yet complete.

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by zqr10159** [comment]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/nginx/NginxCollectImpl.java:56:8: Unused import - org.springframework.util.ObjectUtils. [UnusedImports]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/nginx/NginxCollectImpl.java:56:8: Unused import: org.springframework.util.ObjectUtils. [UnusedImports]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/http/SslCertificateCollectImpl.java:44:1: Extra separation in import group before 'com.fasterxml.jackson.core.format.DataFormatDetector' [ImportOrder]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/http/SslCertificateCollectImpl.java:44:1: Import com.fasterxml.jackson.core.format.DataFormatDetector appears after other imports that it should precede [ImportOrder]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/http/SslCertificateCollectImpl.java:44:8: Unused import - com.fasterxml.jackson.core.format.DataFormatDetector. [UnusedImports]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/http/SslCertificateCollectImpl.java:44:8: Unused import: com.fasterxml.jackson.core.format.DataFormatDetector. [UnusedImports]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/dns/DnsCollectImpl.java:28:1: Extra separation in import group before 'org.apache.commons.collections4.CollectionUtils' [ImportOrder]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/dns/DnsCollectImpl.java:50:1: Extra separation in import group before 'com.google.common.collect.Lists' [ImportOrder]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/dns/DnsCollectImpl.java:50:1: Import com.google.common.collect.Lists appears after other imports that it should precede [ImportOrder]
Error:  /home/runner/work/hertzbeat/hertzbeat/collector/src/main/java/org/apache/hertzbeat/collector/collect/dns/DnsCollectImpl.java:53:1: Extra separation in import group before 'lombok.AllArgsConstructor' [ImportOrder]

**Review by zqr10159 — DISMISSED** [review]

**Comment by zqr10159** [comment]
Still something wrong.

**Comment by dukbong** [comment]
> Still something wrong.


OMG........... sorry 😢 
 I'll fix it as soon as possible.....................

**Comment by zqr10159** [comment]
> > Still something wrong.
> 
> 
> 
> 
> 
> OMG........... sorry 😢 
> 
>  I'll fix it as soon as possible.....................

Don't worry about it.

**Comment by zqr10159** [comment]
@dukbong Hi, I checked the new checkstyle file and found that the import now needs to be sorted alphabetically by package name, I just tested it locally and it worked, but I can't push it to your repository, I hope this helps!

**Comment by zqr10159** [comment]
image
You can run it locally.

**Comment by dukbong** [comment]
Thanks a lot for the help, but I'm currently working without my laptop, so I can't really apply your suggestions properly. 😭😭😭 
If my commits end up causing issues with the open-source management, please let me know!
I don't want to break the code base!!!!!!
If that's the case, I'll sit tight until I get home and fix it properly following your advice! 🏃

**Comment by zqr10159** [comment]
That's fine. Submit it at your convenience.

**Comment by zqr10159** [comment]
> @zqr10159 Thanks a lot for the help, but I'm currently working without my laptop, so I can't really apply your suggestions properly. 😭😭😭 If my commits end up causing issues with the open-source management, please let me know! I don't want to break the code base!!!!!! If that's the case, I'll sit tight until I get home and fix it properly following your advice! 🏃

That's fine. Submit it at your convenience.

**Comment by crossoverJie** [comment]
@dukbong 

Refer to this [link](https://github.com/apache/hertzbeat/blob/master/home/docs/community/code-style-and-quality-guide.md#2-code-checkstyle) to install the plugin in IDEA to fix checkstyle problems more conveniently.

image


You can also run maven's checkstyle plugin directly to check.

image

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
