### PR TITLE
[improve][bugfix]: fix AlertTemplateUtilTest test exception and update code style

### PR DESCRIPTION
**Pull request by yuluo-yx**
## What's changed?

- For #1967 

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi why remove the idea icon.png

**Comment by yuluo-yx** [comment]
> hi why remove the idea icon.png

sorry, my bad. I will restore it.

**Comment by crossoverJie** [comment]
There are some errors about checkstyle.

Please execute this command before submission:

```shell
mvn checkstyle:checkstyle 
```

**Comment by yuluo-yx** [comment]
> There are some errors about checkstyle.
> 
> Please execute this command before submission:
> 
> ```shell
> mvn checkstyle:checkstyle 
> ```
> 
> Maybe you can refer this link: [#1818 (comment)](https://github.com/apache/hertzbeat/pull/1818#issuecomment-2072519437)

tks, I'm dealing with this very difficult problem. 

```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  2.314 s
[INFO] Finished at: 2024-05-12T23:33:54+08:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project hertzbeat-warehouse: Could not resolve dependencies for project org.apache.hertzbeat:hertzbeat-warehouse:jar:2.0-SNAPSHOT: Could not find artifact org.apache.hertzbeat:hertzbeat-common:jar:2.0-SNAPSHOT -> [Help 1]
[ERROR]
```

I'm having this problem, and I'm guessing it's a problem with my local environment 🤔

**Comment by crossoverJie** [comment]
> I'm having this problem, and I'm guessing it's a problem with my local environment

Maybe you can run this cmd first:

```shell
mvn clean install
```

**Comment by yuluo-yx** [comment]
Does the community have an idea style file for this, something like this:

https://github.com/spring-cloud/spring-cloud-build/tree/main/spring-cloud-build-tools/src/main/resources/intellij

**Comment by yuluo-yx** [comment]
> > I'm having this problem, and I'm guessing it's a problem with my local environment
> 
> Maybe you can run this cmd first:
> 
> ```shell
> mvn clean install
> ```

yep, I executed it.

```
$ maven clean install -Dmaven.test.skip=true

[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.8.1:compile (default-compile) on project hertzbeat-common: Fatal error compiling: java.lang.NoSuchFieldError: Class com.sun.tools.javac.tree.JCTree$JCImport does not have member field 'com.sun.tools.javac.tree.JCTree qualid' -> [Help 1]
```

**Comment by crossoverJie** [comment]
> and I find :[stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n](https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n) but it doesn't seem to work for me.

The current version is not compatible with JDK 21, please use JDK 17 for compilation.

**Comment by yuluo-yx** [comment]
> > and I find :[stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n](https://stackoverflow.com/questions/77171270/compilation-error-after-upgrading-to-jdk-21-nosuchfielderror-jcimport-does-n) but it doesn't seem to work for me.
> 
> The current version is not compatible with JDK 21, please use JDK 17 for compilation.
> 
> https://github.com/apache/hertzbeat/blob/master/CONTRIBUTING.md#backend-start

image

**Comment by yuluo-yx** [comment]
Maybe we should beat magic with magic. Let me try clearing my cache.

**Comment by crossoverJie** [comment]
image
Please confirm that the JDK version used by your Maven is JDK 17?

```shell
mvn -version
```

**Comment by yuluo-yx** [comment]
> image Please confirm that the JDK version used by your Maven is JDK 17?
> 
> ```shell
> mvn -version
> ```

```
$ mvn -version
Apache Maven 3.9.0 (9b58d2bad23a66be161c4664ef21ce219c2c8584)
Maven home: D:\environment\Java\apache-maven-3.9.0
Java version: 17.0.1, vendor: Oracle Corporation, runtime: D:\environment\Java\JDK\JKD17
Default locale: zh_CN, platform encoding: GBK
OS name: "windows 10", version: "10.0", arch: "amd64", family: "windows"
```

**Comment by crossoverJie** [comment]
image
This is a bit strange; I cannot reproduce the issue with your code unless I use JDK 21.

**Comment by yuluo-yx** [comment]
Thank you for your help, after I cleared the cache of idea, it works fine! 🫡@crossoverJie

**Review by tomsun28 — APPROVED** [review]

**Pull request merged**
