### PR TITLE
[feature] : support Kimi Ai

### PR DESCRIPTION
**Pull request by Yanshuming1**
support Kimi Ai

### CODE REVIEW

**Comment by tomsun28** [comment]
hi, please fix the https://github.com/apache/hertzbeat/pull/2153 wrong merge in this pr.

**Comment by tomsun28** [comment]
image

**Comment by Yanshuming1** [comment]
> 图像



> 你好，请修复此 pr 中的[#2153错误合并。](https://github.com/apache/hertzbeat/pull/2153)
resolved

**Review by tomsun28 — APPROVED** [review]
👍lgtm

**Pull request merged**
