### PR TITLE
[bugfix] fix alarm threshold ava can not modify

### LINKED ISSUE #2493: [BUG] <Can not Edit Threshold Rule in master code>
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Can not Edit Threshold Rule when use master code 

The click ok button not response. 

image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
HertzBeat version(s): master
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

close #2493 

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Review by Aias00 — CHANGES_REQUESTED** [review]
if the cascade values have been changed first, and recover later, and then click submit . the form can bu submiited. simplely check the cascade values length may can not slove the problem

**Comment by Aias00** [comment]
image
when click submit button first time, the cascade values length is 2 and qbdata is empty;


image
image

modify the cascade value, make it`s length 3, then add a empty rule , it can be submitted successfully, and the rule value will be undifined actually

image

do not remove this empty rule , just change cascade values, and the form can be submitted successfully this time.

**Comment by tomsun28** [comment]
hi, sorry for not got it. Do you means the ` empty rule ` should be verification failed, the form can not be submiited.?  This maybe an another bug.  

The cascade values length only mapping with the Metric Target Switch, if choose the `Availability`, cascade length is 2, if choose others metrics, length is 3. 

image

image

**Comment by Aias00** [comment]
> hi, sorry for not got it. Do you means the `empty rule` should be verification failed, the form can not be submiited.? This maybe an another bug.
> 
> The cascade values length only mapping with the Metric Target Switch, if choose the `Availability`, cascade length is 2, if choose others metrics, length is 3.
> 
> image image

yeap, this empty rule can submitted successfully situation may be another bug. all i want to say, it`s that :
1. if u changed the cascade value to 3 length、add some rule and then change it back to 2 length. it can be submitted; cause  the rules datas were not cleared. and this can let the form check control valid. oh, this may be another bug 🤣
2. when 2 length cascade , the form check control should allows the form`s submiting. and this pr can fix it appropriately

**Review by Aias00 — APPROVED** [review]
lgtm

**Comment by tomsun28** [comment]
> * if u changed the cascade value to 3 length、add some rule and then change it back to 2 length. it can be submitted; cause  the rules datas were not cleared. and this can let the form check control valid. oh, this may be another bug 🤣

Got it thanks, i will fix it.

**Review by kerwin612 — APPROVED** [review]

**Pull request merged**
