### PR TITLE
Refactor: using Reflections to load AbstractCollect

### PR DESCRIPTION
**Pull request by Calvin979**
## What's changed?
Hertzbeat uses SPI to load AbstractCollect, which means anybody who intends to add a new monitor needs to modify SPI file(in the path `META-INF\services`) as well.
Therefore I use Reflections to replace SPI. It will scan concrete class of AbstractCollect and create instance automatically.

**New Dependency**
~~~ maven
<dependency>
        <groupId>org.reflections</groupId>
        <artifactId>reflections</artifactId>
        <version>0.10.2</version>
</dependency>
~~~ 

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
👍👍 Great Idea! 
I see we use the `org.reflections` to reflection, but this package not maintained anymore. https://github.com/ronmamo/reflections/issues/465 
And we will build the graalvm native-image later for hertzbeat, It seems that this package does not support it well. https://github.com/ronmamo/reflections/issues/470

**Comment by Calvin979** [comment]
> 👍👍 Great Idea! I see we use the `org.reflections` to reflection, but this package not maintained anymore. [ronmamo/reflections#465](https://github.com/ronmamo/reflections/issues/465) And we will build the graalvm native-image later for hertzbeat, It seems that this package does not support it well. [ronmamo/reflections#470](https://github.com/ronmamo/reflections/issues/470)

Yeah, looks like it doesn't work on graalvm native-image. Should I close this pr?

**Comment by tomsun28** [comment]
> Yeah, looks like it doesn't work on graalvm native-image. Should I close this pr?

We can keep it now and see how to modify it later, or wait until we make a native image.

**Comment by gcdd1993** [comment]
建议尽量少用反射，SPI配置文件应该不是特别大的负担 @Calvin979 @tomsun28

**Comment by hertzbeat** [comment]
> Bot detected the issue body's language is not English, translate it automatically. 👯👭🏻🧑‍🤝‍🧑👫🧑🏿‍🤝‍🧑🏻👩🏾‍🤝‍👨🏿👬🏿         
----    
It is recommended to use reflection as little as possible. The SPI configuration file should not be a particularly big burden @Calvin979 @tomsun28

**Comment by tomsun28** [comment]
okk, try not to use reflection in higher versions of jdk

**Pull request closed without merging**
