### PR TITLE
[fixbug]fix parameter parsing problem

### LINKED ISSUE #2250: [BUG] Failed to add template
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Failed to add template, caused by PR # 2122
image

### Expected Behavior

_No response_

### Steps To Reproduce

_No response_

### Environment

```markdown
HertzBeat version(s):master
```

### Debug logs

_No response_

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by zhangshenghang**
## What's changed?

fix #2250 

Modify Jackson to ignore the position field instead of throwing an exception directly to make the system unusable

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi, what about this prop, should we conifig it in jackson ObjectMapper

```
  jackson:
    default-property-inclusion: ALWAYS
```

image

**Comment by zhangshenghang** [comment]
> hi, what about this prop, should we conifig it in jackson ObjectMapper
> 
> ```
>   jackson:
>     default-property-inclusion: ALWAYS
> ```
> 
> image

I will modify it

**Comment by zhangshenghang** [comment]
@tomsun28 

## Modifications
Customized ObjectMapper Beans may override Spring Boot's default Jackson configuration.
Use the Jackson2ObjectMapperBuilder provided by Spring to create the ObjectMapper.

## Verification
When set to
```
jackson:
default-property-inclusion: ALWAYS
deserialization:
fail-on-unknown-properties: true
```
Error
image

---

When configured to
```
jackson:
default-property-inclusion: ALWAYS
deserialization:
fail-on-unknown-properties: false
```
Run successfully.

**Comment by tomsun28** [comment]
👍 /cc @Calvin979

**Comment by zqr10159** [comment]
Can application.yml be left unmodified? Unless it's a user-definable item, it's recommended that it be implemented in the code so that users can avoid some problems when upgrading

**Comment by tomsun28** [comment]
> Can application.yml be left unmodified? Unless it's a user-definable item, it's recommended that it be implemented in the code so that users can avoid some problems when upgrading

hi, yes here the old version upgrade no need modify the application.yml due the code has config too. Is that true? @zhangshenghang

**Comment by zhangshenghang** [comment]
> hi, yes here the old version upgrade no need modify the application.yml due the code has config too. Is that true?



> > Can application.yml be left unmodified? Unless it's a user-definable item, it's recommended that it be implemented in the code so that users can avoid some problems when upgrading
> 
> hi, yes here the old version upgrade no need modify the application.yml due the code has config too. Is that true? @zhangshenghang

The code modified in this PR is implemented using 'Jackson2OrderMapperBuilderCustomizer', and can run normally without setting this value in the configuration file. Not setting the value of 'fail on unknown properties' has the same effect as setting the value of' fail on unknown properties: false '. Only when set to true will the above error be prompted.
```
deserialization:
fail-on-unknown-properties: false
```
﻿
If we want to be compatible with older versions, we can remove 'fail-on-unknown-properties: false'
﻿

**Review by tomsun28 — DISMISSED** [review]

**Comment by zhangshenghang** [comment]
> > hi, yes here the old version upgrade no need modify the application.yml due the code has config too. Is that true?
> 
> > > Can application.yml be left unmodified? Unless it's a user-definable item, it's recommended that it be implemented in the code so that users can avoid some problems when upgrading
> > 
> > 
> > hi, yes here the old version upgrade no need modify the application.yml due the code has config too. Is that true? @zhangshenghang
> 
> The code modified in this PR is implemented using 'Jackson2OrderMapperBuilderCustomizer', and can run normally without setting this value in the configuration file. Not setting the value of 'fail on unknown properties' has the same effect as setting the value of' fail on unknown properties: false '. Only when set to true will the above error be prompted.
> 
> ```
> deserialization:
> fail-on-unknown-properties: false
> ```
> 
> ﻿ If we want to be compatible with older versions, we can remove 'fail-on-unknown-properties: false' @tomsun28

@tomsun28 
Do we need to delete this？
```
deserialization:
 fail-on-unknown-properties: false
```

**Comment by tomsun28** [comment]
> Do we need to delete this？

ok, 👍

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
