### PR TITLE
[doc]update threshold alarm doc

### PR DESCRIPTION
**Pull request by zhangshenghang**
## What's changed?

#1932 

- Updated documentation related to threshold alarms
- Delete some expired document content

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.

### CODE REVIEW

**Comment by tomsun28** [comment]
hi thanks, lgtm! Can we provide the english version doc and use english png?

**Comment by zhangshenghang** [comment]
> 嗨，谢谢，lgtm！我们可以提供英文版doc并使用英文png吗？

Yes, I forgot the English documentation, I will add it

**Comment by zhangshenghang** [comment]
Yes, I forgot the English documentation, I will add it

**Comment by zhangshenghang** [comment]
@tomsun28  Hi, English documentation has been updated

**Comment by tomsun28** [comment]
LGTM!👍👍

**Review by tomsun28 — APPROVED** [review]

**Pull request merged**
