### PR TITLE
[improve] Replacing characters with http constants

### PR DESCRIPTION
**Pull request by yuluo-yx**

### CODE REVIEW

**Comment by tomsun28** [comment]
hi, It is recommended that constants that are only used in the collector module be placed in the collector module instead of the common module.

**Comment by yuluo-yx** [comment]
> hi, It is recommended that constants that are only used in the collector module be placed in the collector module instead of the common module.

Meaning in CollectorConstants? 🤔

**Comment by tomsun28** [comment]
> > hi, It is recommended that constants that are only used in the collector module be placed in the collector module instead of the common module.
> 
> Meaning in CollectorConstants? 🤔

move the collector relate constant files into collector module

**Comment by yuluo-yx** [comment]
Okay.i will do it

tomsun28 ***@***.***>于2024年8月11日 周日15:59写道：

**Comment by yuluo-yx** [comment]
ptal again, tks @tomsun28

**Review by tomsun28 — APPROVED** [review]
lgtm 👍

**Review by tomsun28 — APPROVED** [review]

**Pull request merged**
