### PR TITLE
[type:fix] fix threshold rule modal not clear bug

### PR DESCRIPTION
**Pull request by Aias00**
## What's changed?

fix threshold rule modal not clear bug #2276

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by LiuTianyou** [comment]
@Aias00  hi, in my test, the modal can be cleared after canceling the edit, but the form still cannot be cleared after clicking OK

**Comment by Aias00** [comment]
OK i will do more check later

---- Replied Message ----
| From | ***@***.***> |
| Date | 07/22/2024 21:46 |
| To | apache/hertzbeat ***@***.***> |
| Cc | aias00 ***@***.***>,
Mention ***@***.***> |
| Subject | Re: [apache/hertzbeat] [type:fix] fix threshold rule modal not clear bug (PR #2340) |

@Aias00 hi, in my test, the modal can be cleared after canceling the edit, but the form still cannot be cleared after clicking OK

**Comment by Aias00** [comment]
@LiuTianyou hi, i had checked again, and now the form will be cleared after clicking ok. pls check later

**Review by LiuTianyou — APPROVED** [review]

**Comment by LiuTianyou** [comment]
👍🏻👍🏻👍🏻

**Pull request merged**
