### PR TITLE
[chore] optimize e2e folder struct

### PR DESCRIPTION
**Pull request by yuluo-yx**
optimize e2e folder struct

### CODE REVIEW

**Comment by tomsun28** [comment]
hi personally, I think testsuite.yaml should not be placed in the data directory, just keep the status quo.

**Comment by tomsun28** [comment]
image
hi, is this the reason why move the testsuite.yaml ?

**Comment by yuluo-yx** [comment]
> hi personally, I think testsuite.yaml should not be placed in the data directory, just keep the status quo.

got it. I will restore it.

**Comment by yuluo-yx** [comment]
> image hi, is this the reason why move the testsuite.yaml ?

no, here are some of my personal thoughts, I think these are data configurations and the e2e tests are occasional errors. It can't be reproduced locally, and I'm looking into keeping a running log of the system in github ci.

**Comment by yuluo-yx** [comment]
@tomsun28 restore it, ptal

**Review by tomsun28 — APPROVED** [review]

**Pull request merged**
