### PR TITLE
[improve] Improve markdown md035

### LINKED ISSUE #2574: [Task] Optimize historical Markdown file format
### Description

We have changed the Markdown formatting tool to Markdownlint, which can set rules more comprehensively. At the same time, some new tasks have been added. Setting rules will cause a lot of history files to be modified.

It is divided into the following tasks. If you are interested, you can claim them yourself.

image

rule description : https://github.com/DavidAnson/markdownlint/blob/main/doc/Rules.md

|task|assignee|complete status|
|---|---|---|
|MD001|@tomsun28|✅|
|MD003|@Calvin979||
|MD013|||
|MD024|@zhangshenghang|✅|
|MD025|@Aias00||
|MD029|@pwallk ||
|MD033|||
|MD035|||
|MD036|||
|MD040|||
|MD041|@zhangshenghang||
|MD045|||
|MD046|||
|MD047|@LiuTianyou||
|MD052|||

### Task List

_No response_

### PR DESCRIPTION
**Pull request by zhangshenghang**
## What's changed?

-  For #2574

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by Calvin979** [comment]
Issue #2574 will be closed if you linked it on this pr. @zhangshenghang

**Comment by zhangshenghang** [comment]
> #2574



> Issue #2574 will be closed if you linked it on this pr. @zhangshenghang

@Calvin979 Thank you for your reminder. Is there any way to link it without closing it

**Comment by Calvin979** [comment]
> > #2574
> 
> > Issue #2574 will be closed if you linked it on this pr. @zhangshenghang
> 
> @Calvin979 Thank you for your reminder. Is there any way to link it without closing it

Looks like the only way we can do is to reopen #2574 again.

**Comment by yuluo-yx** [comment]
Instead of using fix or fixed followed by the issue number, you can use For or Of to convey the meaning.

more information: https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue

@Calvin979 /cc @zhangshenghang

**Review by yuluo-yx — APPROVED** [review]
LGTM.

**Comment by zhangshenghang** [comment]
> Instead of using fix or fixed followed by the issue number, you can use For or Of to convey the meaning.
> 
> more information: https://docs.github.com/zh/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue
> 
> @Calvin979 /cc @zhangshenghang

@yuluo-yx  Nice , By default there is no prefix. Is it ok to just write #xxx?

**Comment by yuluo-yx** [comment]
yep, It depends on personal preference. I prefer to use `for`.

Jast ***@***.***>于2024年8月25日 周日10:59写道：

**Pull request merged**
