### PR TITLE
[improve] add i18n for postgresql\kingbase\greenplum

### PR DESCRIPTION
**Pull request by Aias00**
## What's changed?

add i18n for postgresql\kingbase\greenplum

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by Aias00** [comment]
hi, my workflow errors several times at this step, and i don`t konw why
image

**Comment by yuluo-yx** [comment]
> hi, my workflow errors several times at this step, and i don`t konw why image

I've submitted a pr to fix it. pls see: #2447

**Comment by Aias00** [comment]
> > hi, my workflow errors several times at this step, and i don`t konw why image
> 
> I've submitted a pr to fix it. pls see: #2447

hi, nice one 👍👍👍

**Comment by yuluo-yx** [comment]
> hi, nice one 👍👍👍

tks, if has any problem, pls @ me.

**Review by tomsun28 — APPROVED** [review]
lgtm 👍

**Pull request merged**
