### PR TITLE
chore: make the controller response be easy

### PR DESCRIPTION
**Pull request by LinuxSuRen**
## What's changed?

Below is the test result

image

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Review by yuluo-yx — APPROVED** [review]
LGTM

**Comment by yuluo-yx** [comment]
ptal @tomsun28 @zqr10159

**Review by tomsun28 — APPROVED** [review]
👍 lgtm

**Comment by Calvin979** [comment]
How about use `ResponseBodyAdvice` to handle response entity globally? @tomsun28 @LinuxSuRen

**Comment by LinuxSuRen** [comment]
I'm not sure if all controllers could have the same or similar way to handle it.

**Comment by tomsun28** [comment]
+1 the response stru may not always same

**Pull request merged**
