### PR TITLE
[Fix] fix clickhouse monitor

### PR DESCRIPTION
**Pull request by LiuTianyou**
## What's changed?

1. Fix the problem that clickhouse monitoring cannot be used normally #2872 

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Review by Calvin979 — APPROVED** [review]

**Comment by tomsun28** [comment]
A bit confused🐶🐶, why change the ping_available -> summary then it works

**Comment by Calvin979** [comment]
> A bit confused🐶🐶, why change the ping_available -> summary then it works

Looks like it is caused by #2266

**Review by Calvin979 — CHANGES_REQUESTED** [review]
I think it is better to change code in `HttpCollectImpl`

**Comment by tomsun28** [comment]
> I think it is better to change code in `HttpCollectImpl`

Agree, metrics are not recommended to be hardcoded in code

**Review by yuluo-yx — DISMISSED** [review]

**Comment by LiuTianyou** [comment]
> I think it is better to change code in `HttpCollectImpl`

hi, #2266 In order for http protocol collection to support obtaining data from response headers, should we add a parsing type as `response_header` and obtain the header data corresponding to the metrics name?

**Comment by Calvin979** [comment]
> > I think it is better to change code in `HttpCollectImpl`
> 
> hi, #2266 In order for http protocol collection to support obtaining data from response headers, should we add a parsing type as `response_header` and obtain the header data corresponding to the metrics name?

Yes, it is better than hard code

**Review by Calvin979 — APPROVED** [review]
LGTM

**Pull request merged**
