### PR TITLE
[improve]add Plc protocol , Modbus monitor

### PR DESCRIPTION
**Pull request by ZY945**
## What's changed?

The plc4x project is used to implement the collection of PLC protocol. Currently, the retention register and coil collection of modBus protocol have been introduced, which can collect data from different slave devices with the same IP address

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by ZY945** [comment]
I found that pltConnectivity close() takes a long time, mostly 2000ms, and may need to be optimized by reusing connections or asynchronously closing connections

**Comment by pwallk** [comment]
hi, since I often use Modbus and other related communication protocols in my work, I am very interested in this PR. I pulled the code and it took me a while to figure out how to use it and successfully read the data, right.In this regard, I have some questions or suggestions:
1.Modbus data is converted into actual data, for example: the read data is of type `Double`, occupies four registers, the byte sequence is `CDAB`, and the read address is `1[4]`. The program should support the conversion of the values of four registers into actual data, after all, the monitoring needs to alarm the actual values
PixPin_2024-12-03_15-41-56
2.the `PlcProtocol` and `PlcCollectImpl` classes are coupled to Modbus TCP，it is difficult to develop other communication protocols in the future，is there any way to decouple them? Such as 
```java
@Slf4j
public abstract class AbstractPlcCollectImpl extends AbstractCollect {

    private static final PlcConnectionManager CONNECTION_MANAGER;

    static {
        CONNECTION_MANAGER = PlcDriverManager.getDefault().getConnectionManager();
    }

    @Override
    public void collect(CollectRep.MetricsData.Builder builder, long monitorId, String app, Metrics metrics) {
        // do something....
        String connectionString =getConnectionString(metrics);
        PlcConnection plcConnection = CONNECTION_MANAGER.getConnection(connectionString);
        PlcReadRequest readRequest = buildRequest(metrics, plcConnection);
        // do something....

    }

    protected abstract String getConnectionString(Metrics metrics);
    
    protected abstract PlcReadRequest buildRequest(Metrics metrics, PlcConnection connection);
}

public class ModbusCollectImpl extends AbstractPlcCollectImpl{
    @Override
    protected String getConnectionString(Metrics metrics) {
        ModbusProtocol protocol = metrics.getModbusProtocol();
        // do something...
    }

    @Override
    protected PlcReadRequest buildRequest(Metrics metrics, PlcConnection connection) {
        // do something...
    }

    @Override
    public void preCheck(Metrics metrics) throws IllegalArgumentException {
        // do something...
    }

    @Override
    public String supportProtocol() {
        return "MODBUS";
    }
}
```

**Comment by ZY945** [comment]
> hi, since I often use Modbus and other related communication protocols in my work, I am very interested in this PR. I pulled the code and it took me a while to figure out how to use it and successfully read the data, right.In this regard, I have some questions or suggestions: 1.Modbus data is converted into actual data, for example: the read data is of type `Double`, occupies four registers, the byte sequence is `CDAB`, and the read address is `1[4]`. The program should support the conversion of the values of four registers into actual data, after all, the monitoring needs to alarm the actual values PixPin_2024-12-03_15-41-56 2.the `PlcProtocol` and `PlcCollectImpl` classes are coupled to Modbus TCP，it is difficult to develop other communication protocols in the future，is there any way to decouple them? Such as
> 
> ```java
> @Slf4j
> public abstract class AbstractPlcCollectImpl extends AbstractCollect {
> 
>     private static final PlcConnectionManager CONNECTION_MANAGER;
> 
>     static {
>         CONNECTION_MANAGER = PlcDriverManager.getDefault().getConnectionManager();
>     }
> 
>     @Override
>     public void collect(CollectRep.MetricsData.Builder builder, long monitorId, String app, Metrics metrics) {
>         // do something....
>         String connectionString =getConnectionString(metrics);
>         PlcConnection plcConnection = CONNECTION_MANAGER.getConnection(connectionString);
>         PlcReadRequest readRequest = buildRequest(metrics, plcConnection);
>         // do something....
> 
>     }
> 
>     protected abstract String getConnectionString(Metrics metrics);
>     
>     protected abstract PlcReadRequest buildRequest(Metrics metrics, PlcConnection connection);
> }
> 
> public class ModbusCollectImpl extends AbstractPlcCollectImpl{
>     @Override
>     protected String getConnectionString(Metrics metrics) {
>         ModbusProtocol protocol = metrics.getModbusProtocol();
>         // do something...
>     }
> 
>     @Override
>     protected PlcReadRequest buildRequest(Metrics metrics, PlcConnection connection) {
>         // do something...
>     }
> 
>     @Override
>     public void preCheck(Metrics metrics) throws IllegalArgumentException {
>         // do something...
>     }
> 
>     @Override
>     public String supportProtocol() {
>         return "MODBUS";
>     }
> }
> ```

Thank you very much for your suggestion, I will try to make changes.

**Comment by ZY945** [comment]
I have a question, does Modbus frequently disconnect after each data acquisition, or should the connection be maintained 

If we need to maintain the connection continuously, I have a suggestion to create a class specifically for managing the connection, and then initialize the background thread in it to determine whether the monitoring where the current connection is located is still in the startup state. If it is disabled, disconnect the connection. I don't know if this idea is correct

**Comment by pwallk** [comment]
> I have a question, does Modbus frequently disconnect after each data acquisition, or should the connection be maintained
> 
> If we need to maintain the connection continuously, I have a suggestion to create a class specifically for managing the connection, and then initialize the background thread in it to determine whether the monitoring where the current connection is located is still in the startup state. If it is disabled, disconnect the connection. I don't know if this idea is correct

Maybe it should be left to the user to choose

**Review by boyucjz — COMMENTED** [review]
No problem with the code

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
