### PR TITLE
[feature] Desensitize sensitive information.

### PR DESCRIPTION
**Pull request by ayu-v0**
## What's changed?
https://github.com/apache/hertzbeat/issues/2792

This PR desensitizes the phone and email, while ensuring that the desensitized data cannot be submitted to the database.
The desensitization rule for a email is to replace it with a "." to make the email illegal and ensure that it cannot be submitted directly to the database.The same goes for cell phone numbers.

Here is a picture of the modification operation：
p1
p2

The following is the information of the database：
p3
p4
## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
relate with https://github.com/apache/hertzbeat/pull/2800

**Comment by ayu-v0** [comment]
The merge error is caused by @date and @Description, I've fixed it @yuluo-yx

**Comment by tomsun28** [comment]
hi @ayu-v0 thanks for this pr. 
I reviewed and found that this implementation is not very reasonable. In case user modify the old data, eg: receiver name, phone. Its impact will make people feel confused and think it is a bug.
and another case like send test alram, it will use the serialize data de...@qq.com to send email and failed.
Suggest suspend this issue, investigate the desensitization methods of other platforms later.

**Comment by tomsun28** [comment]
Sorry for rejecting this PR you worked so hard on.

**Comment by ayu-v0** [comment]
> Sorry for rejecting this PR you worked so hard on.

Thank you very much for your review. This PR may be because I considered that the desensitized data is the correct information that the user has verified, so I did not consider that the user might send the email with the desensitized information. Based on this scenario, I wonder if there are any solutions (if I can think of them, haha).

**Pull request closed without merging**
