### PR TITLE
[bugfix] Java 8 date/time type `LocalDateTime` not supported by default

### PR DESCRIPTION
**Pull request by yuluo-yx**
- For #2485
- refer: https://github.com/apache/hertzbeat/pull/2454#issuecomment-2272585380

### CODE REVIEW

**Comment by pwallk** [comment]
Perhaps adding `jackson-datatype-jsr310` would be a better choice,such as 
```java
    @Bean
    public Jackson2ObjectMapperBuilderCustomizer customizer() {
        return builder -> {
            JavaTimeModule javaTimeModule = new JavaTimeModule();
            final SimpleDateFormat simpleDateFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ss.SSSX");
            simpleDateFormat.setTimeZone(TimeZone.getDefault());

            javaTimeModule.addSerializer(BigDecimal.class, ToStringSerializer.instance);
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("yyyy-MM-dd'T'HH:mm:ss.SSSX");
            javaTimeModule.addSerializer(LocalDateTime.class, new LocalDateTimeSerializer(formatter));
            javaTimeModule.addDeserializer(LocalDateTime.class, new LocalDateTimeDeserializer(formatter));

            builder.modules(javaTimeModule)
                    .timeZone(TimeZone.getDefault())
                    .dateFormat(simpleDateFormat)
        };
    }

**Comment by pwallk** [comment]
The example is rough, `DateTimeFormatter` does not support `yyyy-MM-dd'T 'hh :mm:ss.SSSX`, change to `yyyy-MM-dd HH:mm:ss.SSSSSS`

**Comment by yuluo-yx** [comment]
> The example is rough, `DateTimeFormatter` does not support `yyyy-MM-dd'T 'hh :mm:ss.SSSX`, change to `yyyy-MM-dd'T'HH:mm:ss.SSSSSS`

In the demo you provided, the time format is also. And the previous code was in this date format, is there any advantage to changing it?
image

**Comment by pwallk** [comment]
Just to demonstrate how `jackson` supports `LocalDateTime`, the time format can be changed as needed,

**Comment by yuluo-yx** [comment]
> Just to demonstrate how `jackson` supports `LocalDateTime`, the time format can be changed as needed,

cc @tomsun28. Do you have any ideas for this pr

**Comment by Calvin979** [comment]
@yuluo-yx Maybe you can refer #2122 to find out why LocalDateTime is supported by default.
Is the time correct in db on your pr?

**Comment by tomsun28** [comment]
hi, this also related the pr https://github.com/apache/hertzbeat/pull/2251

**Comment by yuluo-yx** [comment]
> hi, this also related the pr #2251

Looks like there's a lot riding on this one. 🥲🥲

**Comment by yuluo-yx** [comment]
I'm going to close this pr for now, looking for a better solution in #2454

**Comment by yuluo-yx** [comment]
I'm going to close this pr for now, looking for a better solution in #2454

**Pull request closed without merging**
