### PR TITLE
[feature] Add Apache Hbase RegionServer monitoring

### PR DESCRIPTION
**Pull request by zhangshenghang**
## What's changed?
#1822 
- Add Apache Hbase RegionServer monitoring
- Add Apache Hbase RegionServer monitoring documentation

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.

### CODE REVIEW

**Comment by tomsun28** [comment]
LGTM! Btw, we can edit here to add helo doc menu. https://github.com/apache/hertzbeat/blob/master/home/sidebars.json#L215

**Review by tomsun28 — DISMISSED** [review]

**Comment by zhangshenghang** [comment]
> LGTM！顺便说一句，我们可以在这里编辑以添加 helo 文档菜单。https://github.com/apache/hertzbeat/blob/master/home/sidebars.json#L215

okey

**Comment by zhangshenghang** [comment]
> LGTM! Btw, we can edit here to add helo doc menu. https://github.com/apache/hertzbeat/blob/master/home/sidebars.json#L215

Sidebars have been updated @tomsun28

**Review by tomsun28 — APPROVED** [review]
LGTM!👍👍

**Pull request merged**
