### PR TITLE
[optimize] In a minor issue, the values of max and min are reversed

### PR DESCRIPTION
**Pull request by lixiaobaivv**
- The SQL query is reversed from the actual value；

23png

### CODE REVIEW

**Review by LinuxSuRen — COMMENTED** [review]
I'm wondering if it's possible to add new unit tests to cover those cases. And thanks for your time.

**Comment by yuluo-yx** [comment]
> I'm wondering if it's possible to add new unit tests to cover those cases. And thanks for your time.

+1, good idea.

**Comment by lixiaobaivv** [comment]
> > 我想知道是否可以添加新的单元测试来涵盖这些情况。谢谢您的宝贵时间。
> 
> +1，好主意。

Sorry, this is my first time submitting a PR. If there is anything wrong, I will improve it. Here is a screenshot of my unit test passing!

**Comment by lixiaobaivv** [comment]
> 您可以添加一些新的单元测试来确保您的更改正确无误。我们这样做是因为没有测试人员来测试新的更改。
> 
> 当然，这只是我的个人建议。维护者可能会做出合并决定。

Hello, when I was writing unit tests, I found that there was already a reusable test method. I tested the getMetricHistoryData method under the MetricsDataControllerTest class and it passed.

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
