### PR TITLE
[feature] add influxdb metrics monitoring 

### PR DESCRIPTION
**Pull request by TJxiaobao**
## What's changed?

influxdb monitoring indicators are added.
image

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.com/docs/others/contributing/)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](../e2e) and all cases have passed.

### CODE REVIEW

**Review by tomsun28 — APPROVED** [review]
LGTM!👍

**Comment by tomsun28** [comment]
link https://github.com/dromara/hertzbeat/pull/1717

**Comment by tomsun28** [comment]
👍 btw we can modify here https://github.com/dromara/hertzbeat/blob/master/home/sidebars.json#L129 to add influxdb menu in home website

**Comment by TJxiaobao** [comment]
Okay, I'll give it a try.

**Review by tomsun28 — APPROVED** [review]

**Pull request merged**
