### PR TITLE
[Improve] Support jacoco and Codecov

### PR DESCRIPTION
**Pull request by crossoverJie**
## What's changed?

Support `jacoco` and `Codecov`.

Before merging, @tomsun28 need to obtain the secret from [Codecov](https://app.codecov.io/gh/apache/hertzbeat/) management console.

And create this secret in the [repo](https://github.com/apache/hertzbeat/settings/secrets/actions/new).

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by crossoverJie** [comment]
I have tested it in my [own repo](https://github.com/crossoverJie/hertzbeat/pull/4).

**Comment by tomsun28** [comment]
ok👍

**Review by yuluo-yx — APPROVED** [review]
lgtm

**Review by tomsun28 — APPROVED** [review]
token has added. merge.

**Comment by tomsun28** [comment]
https://app.codecov.io/gh/apache/hertzbeat

**Pull request merged**
