### PR TITLE
Feature: Support discovery monitoring instance through http_sd

### PR DESCRIPTION
**Pull request by Calvin979**
## What's changed?

Corresponding issue:
#1625 

Service discovery can be available for all collectors now and I provide http_sd as a deafult strategy.  
There's something different between one time task and cyclic task while fetching instance info:
1. one time task
image
2. cyclic task
image

**How to add service discovery for collector?**
1. implements `CommonProtocol` interface
image
2. add param field like http_sd in yml
image
~~~yml
  - field: http_sd
    name:
      zh-CN: http_sd
      en-US: http_sd
    type: text
    placeholder: Enter http_sd url
    required: false
    hide: true
~~~
3. override method `getSupportProtocolClass` and point out which protocol is used for current collector
image

**Test result**
01测试连接成功
02监控详情

**What's more**
the priority of sd is higher than host, which means it will use sd first if you config host and http_sd simultaneously.

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [x]  I have written the necessary doc or comment.
- [x]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [x] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by Calvin979** [comment]
I haven't add sd for any collectors, it needs to be discussed which collector should support for sd

**Comment by tomsun28** [comment]
👍👍 This design implementation is eye-catching and is a good idea. I don't seem to find the part that automatically discovers and creates multiple instances through the information returned by the http_sd interface. For example, http_sd returns ip1-port1 ip2-port2 ip3-port3. We create three new monitoring instances based on these three automatic discoveries.

**Comment by Calvin979** [comment]
@tomsun28 
I'm not sure whether you mean we need to create monitor task automatically. If so, the process is different.
Monitor task must be created and managed by `Manager`, then collector should collect sd data as a cyclic task like this:
image


What I coded in this pr is **update host and port automatically**.
image
It will be helpful for monitoring services that are supported for automatic failover like `Redis sentinel`.

**Comment by tomsun28** [comment]
hi yes, the first design like this as same as your.


image

image
 

Also i think this pr design is great, provides another way of thinking. how about combine the two. Our initial goal is to support automatic maintenance of batch monitoring tasks through the data returned by http_sd.

**Comment by Calvin979** [comment]
@tomsun28 
Thanks for your design. It is a more clear design than my design. Should I modify code in this pr directly?🤣🤣

**Comment by tomsun28** [comment]
👍👍 okay okay. It is not urgent, depends on your time.  Recommend to release an first apache version first and after then consider integrate this big feature.

**Comment by Calvin979** [comment]
> 👍👍 okay okay. It is not urgent, depends on your time. Recommend to release an first apache version first and after then consider integrate this big feature.

OK, I will close this pr. And I will open another pr after first apache version released and I finished this new feature.

**Pull request closed without merging**
