### PR TITLE
[doc]update doc for custom plugin

### PR DESCRIPTION
**Pull request by LiuTianyou**
## What's changed?

1. update doc for custom plugin  #2173

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by zqr10159** [comment]
Lgtm,but I suggest to merge it after the new version is released to avoid user misunderst和ing, or how about we provide dev docs 和 release docs? @tomsun28

**Comment by tomsun28** [comment]
> Lgtm,but I suggest to merge it after the new version is released to avoid user misundersting, or how about we provide dev docs 和 release docs? @tomsun28

ok, we can merge it when new version released.

**Review by zqr10159 — DISMISSED** [review]

**Comment by zqr10159** [comment]
@LiuTianyou Please resolve conflicts,I will merge it later.

**Comment by LiuTianyou** [comment]
@zqr10159  hi，I resolved the conflict and modified the documentation according to the latest plugin implementation

**Comment by zqr10159** [comment]
> @zqr10159 hi，I resolved the conflict and modified the documentation according to the latest plugin implementation

lgtm!

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
