### PR TITLE
[improve] use eclipselink orm replace of hibernate orm

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

use eclipselink orm replace of hibernate orm, due hibernate core licenses is lgpl. 

eclipselink is another implement for jpa guide

## Checklist

- [x]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Comment by tomsun28** [comment]
fatal error, eclipselink auto create some table failed but no log 😂

**Comment by tomsun28** [comment]
[EL Finest]: ddl: 2024-04-22 17:40:41.325--Thread(Thread[main,5,main])--The table (hzb_notice_template) could not be created due to exception: 
Internal Exception: org.h2.jdbc.JdbcSQLSyntaxErrorException: Syntax error in SQL statement "CREATE TABLE hzb_notice_template (ID BIGINT [*]IDENTITY NOT NULL, CONTENT LONGVARCHAR, CREATOR VARCHAR, GMTCREATE TIMESTAMP, GMTUPDATE TIMESTAMP, MODIFIER VARCHAR, NAME VARCHAR, PRESET boolean default false, TYPE SMALLINT, PRIMARY KEY (ID))"; expected "UNSIGNED, ARRAY, INVISIBLE, VISIBLE, NOT NULL, DEFAULT, GENERATED, ON UPDATE, NOT NULL, DEFAULT ON NULL, SEQUENCE, SELECTIVITY, COMMENT, CONSTRAINT, COMMENT, PRIMARY KEY, UNIQUE, NOT NULL, CHECK, REFERENCES, ,, )"; SQL statement:
CREATE TABLE hzb_notice_template (ID BIGINT IDENTITY NOT NULL, CONTENT LONGVARCHAR, CREATOR VARCHAR, GMTCREATE TIMESTAMP, GMTUPDATE TIMESTAMP, MODIFIER VARCHAR, NAME VARCHAR, PRESET boolean default false, TYPE SMALLINT, PRIMARY KEY (ID)) [42001-224]
Error Code: 42001
Call: CREATE TABLE hzb_notice_template (ID BIGINT IDENTITY NOT NULL, CONTENT LONGVARCHAR, CREATOR VARCHAR, GMTCREATE TIMESTAMP, GMTUPDATE TIMESTAMP, MODIFIER VARCHAR, NAME VARCHAR, PRESET boolean default false, TYPE SMALLINT, PRIMARY KEY (ID))
Query: DataModifyQuery(sql="CREATE TABLE hzb_notice_template (ID BIGINT IDENTITY NOT NULL, CONTENT LONGVARCHAR, CREATOR VARCHAR, GMTCREATE TIMESTAMP, GMTUPDATE TIMESTAMP, MODIFIER VARCHAR, NAME VARCHAR, PRESET boolean default false, TYPE SMALLINT, PRIMARY KEY (ID))")

**Comment by tomsun28** [comment]
**upgrade this attention.**  If you use an empty database, there is no need to upgrade.

1. Export Import Method (suggest)

export the all monitoring, export all alarm rules, and deploy start a new one system, import them. 

2. Database Method

edit the h2 database columns, if use mysql, change the mysql columns

```
ALTER TABLE HZB_PARAM  ALTER COLUMN  "value" RENAME TO  param_value;

ALTER TABLE HZB_TAG ALTER COLUMN "value" RENAME TO  tag_value;

ALTER TABLE HZB_STATUS_PAGE_HISTORY ALTER COLUMN "unknown" RENAME TO  unknowing;
```
start the system. 

edit the save all notice rule in web.

**Comment by zqr10159** [comment]
> **upgrade this attention.** If you use an empty database, there is no need to upgrade.
> 
> 1. Export Import Method (suggest)
> 
> export the all monitoring, export all alarm rules, and deploy start a new one system, import them.
> 
> 2. Database Method
> 
> edit the h2 database columns, if use mysql, change the mysql columns
> 
> ```
> ALTER TABLE HZB_PARAM  ALTER COLUMN  "value" RENAME TO  param_value;
> 
> ALTER TABLE HZB_TAG ALTER COLUMN "value" RENAME TO  tag_value;
> 
> ALTER TABLE HZB_STATUS_PAGE_HISTORY ALTER COLUMN "unknown" RENAME TO  unknowing;
> ```
> 
> start the system.
> 
> edit the save all notice rule in web, disable and enable them.
The mysql 5.7 version is not able to execute these sql's and I think upgrading these is best for the user not to operate, can we find a better way?

**Comment by tomsun28** [comment]
> The mysql 5.7 version is not able to execute these sql's and I think upgrading these is best for the user not to operate, can we find a better way?

hi these sql are for h2 database, mysql version we can use navicat console or others to edit table column name here.

```
ALTER TABLE HZB_PARAM CHANGE COLUMN `value` param_value VARCHAR(255);

ALTER TABLE HZB_TAG CHANGE COLUMN `value` tag_value VARCHAR(255);

ALTER TABLE HZB_STATUS_PAGE_HISTORY CHANGE COLUMN `unknown` unknowing VARCHAR(255);
```

For the suggest upgrading, is the Export Import Method. Deploy an new empty system and them import the monitors.

**Comment by zqr10159** [comment]
Is it possible to determine the current version at program startup and execute sql automatically?

**Comment by tomsun28** [comment]
flyway or liquibase can do this, maybe we can consider use flyway to execute version update sql automatically. 
Use jpa auto create tables and use flyway auto upgrde sql change. 
I can try it in anothor new pr.

**Comment by zqr10159** [comment]
> Flyway

sounds good.

**Review by zqr10159 — APPROVED** [review]

**Pull request merged**
