### PR TITLE
[improve] optimize collect thread prevent cpu idling

### PR DESCRIPTION
**Pull request by tomsun28**
## What's changed?

 optimize collect thread prevent cpu idling

refer https://github.com/apache/hertzbeat/pull/2466

## Checklist

- [ ]  I have read the [Contributing Guide](https://hertzbeat.apache.org/docs/community/code_style_and_quality_guide)
- [ ]  I have written the necessary doc or comment.
- [ ]  I have added the necessary unit tests and all cases have passed.

## Add or update API

- [ ] I have added the necessary [e2e tests](https://github.com/apache/hertzbeat/tree/master/e2e) and all cases have passed.

### CODE REVIEW

**Review by yuluo-yx — APPROVED** [review]

**Comment by tomsun28** [comment]
fix io.lettuce.core.resource.DefaultClientResources was not shut down properly, shutdown() was not called before it's garbage-collected. Call shutdown() or shutdown(long,long,TimeUnit)

**Comment by yuluo-yx** [comment]
@tomsun28 there seems to be some issues with this code update, ci keeps running and getting stuck:

image

**Comment by tomsun28** [comment]
> @tomsun28 there seems to be some issues with this code update, ci keeps running and getting stuck:

👍 got it, i try to fix.

**Review by Yanshuming1 — APPROVED** [review]
pass

**Pull request merged**
